const endpoints = {
	cacheBust: `https://congress.api.sunlightfoundation.com/legislators/locate?badParam=badVal`,
	sunlightZIPSearch: `https://congress.api.sunlightfoundation.com/legislators/locate?zip=`,
	repLinks: {
		facebook: '',
		govTrack: 'https://www.govtrack.us/congress/members/[REP_ID]',
		twitter: '',
		youtube: ''
	}
}

const states = [
	{ stateName:'Alabama', abbv: 'AL' },
	{ stateName:'Alaska', abbv: 'AK' },
	{ stateName:'Arizona', abbv: 'AZ' },
	{ stateName:'Arkansas', abbv: 'AR' },
	{ stateName:'California', abbv: 'CA' },
	{ stateName:'Colorado', abbv: 'CO' },
	{ stateName:'Connecticut', abbv: 'CT' },
	{ stateName:'Delaware', abbv: 'DE' },
	{ stateName:'Florida', abbv: 'FL' },
	{ stateName:'Georgia', abbv: 'GA' },
	{ stateName:'Hawaii', abbv: 'HI' },
	{ stateName:'Idaho', abbv: 'ID' },
	{ stateName:'Illinois', abbv: 'IL' },
	{ stateName:'Indiana', abbv: 'IN' },
	{ stateName:'Iowa', abbv: 'IA' },
	{ stateName:'Kansas', abbv: 'KS' },
	{ stateName:'Kentucky', abbv: 'KY' },
	{ stateName:'Louisiana', abbv: 'LA' },
	{ stateName:'Maine', abbv: 'ME' },
	{ stateName:'Maryland', abbv: 'MD' },
	{ stateName:'Massachusetts', abbv: 'MA' },
	{ stateName:'Michigan', abbv: 'MI' },
	{ stateName:'Minnesota', abbv: 'MN' },
	{ stateName:'Mississippi', abbv: 'MS' },
	{ stateName:'Missouri', abbv: 'MO' },
	{ stateName:'Montana', abbv: 'MT' },
	{ stateName:'Nebraska', abbv: 'NE' },
	{ stateName:'Nevada', abbv: 'NV' },
	{ stateName:'New Hampshire', abbv: 'NH' },
	{ stateName:'New Jersey', abbv: 'NJ' },
	{ stateName:'New Mexico', abbv: 'NM' },
	{ stateName:'New York', abbv: 'NY' },
	{ stateName:'North Carolina', abbv: 'NC' },
	{ stateName:'North Dakota', abbv: 'ND' },
	{ stateName:'Ohio', abbv: 'OH' },
	{ stateName:'Oklahoma', abbv: 'OK' },
	{ stateName:'Oregon', abbv: 'OR' },
	{ stateName:'Pennsylvania', abbv: 'PA' },
	{ stateName: 'Rhode Island', abbv: 'RI' },
	{ stateName:'South Carolina', abbv: 'SC' },
	{ stateName:'South Dakota', abbv: 'SD' },
	{ stateName:'Tennessee', abbv: 'TN' },
	{ stateName:'Texas', abbv: 'TX' },
	{ stateName:'Utah', abbv: 'UT' },
	{ stateName:'Vermont', abbv: 'VT' },
	{ stateName:'Virginia', abbv: 'VA' },
	{ stateName:'Washington', abbv: 'WA' },
	{ stateName:'West Virginia', abbv: 'WV' },
	{ stateName:'Wisconsin', abbv: 'WI' },
	{ stateName:'Wyoming', abbv: 'WY' }
]

// zip 60603
const sampleResponseText = `[
  {
    "bioguide_id": "D000622",
    "birthday": "1968-03-12",
    "chamber": "senate",
    "contact_form": "https://www.duckworth.senate.gov/content/contact-senator",
    "crp_id": "N00027860",
    "district": null,
    "facebook_id": "112300955610529",
    "fax": null,
    "fec_ids": [
      "H6IL06141",
      "S6IL00292"
    ],
    "first_name": "Tammy",
    "gender": "F",
    "govtrack_id": "412533",
    "icpsr_id": 21325,
    "in_office": true,
    "last_name": "Duckworth",
    "leadership_role": null,
    "lis_id": "S386",
    "middle_name": null,
    "name_suffix": null,
    "nickname": null,
    "oc_email": "Sen.Duckworth@opencongress.org",
    "ocd_id": "ocd-division/country:us/state:il",
    "office": "G12 Dirksen Senate Office Building",
    "party": "D",
    "phone": "202-224-2854",
    "senate_class": 3,
    "state": "IL",
    "state_name": "Illinois",
    "state_rank": "junior",
    "term_end": "2023-01-03",
    "term_start": "2017-01-03",
    "thomas_id": "02123",
    "title": "Sen",
    "twitter_id": "SenDuckworth",
    "votesmart_id": 57442,
    "website": "https://www.duckworth.senate.gov",
    "youtube_id": "repduckworth"
  },
  {
    "bioguide_id": "D000096",
    "birthday": "1941-09-06",
    "chamber": "house",
    "contact_form": null,
    "crp_id": "N00004884",
    "district": 7,
    "facebook_id": "280757931935749",
    "fax": "202-225-5641",
    "fec_ids": [
      "H4IL07037"
    ],
    "first_name": "Danny",
    "gender": "M",
    "govtrack_id": "400093",
    "icpsr_id": 29717,
    "in_office": true,
    "last_name": "Davis",
    "leadership_role": null,
    "middle_name": "K.",
    "name_suffix": null,
    "nickname": null,
    "oc_email": "Rep.Davis@opencongress.org",
    "ocd_id": "ocd-division/country:us/state:il/cd:7",
    "office": "2159 Rayburn House Office Building",
    "party": "D",
    "phone": "202-225-5006",
    "state": "IL",
    "state_name": "Illinois",
    "term_end": "2019-01-03",
    "term_start": "2017-01-03",
    "thomas_id": "01477",
    "title": "Rep",
    "twitter_id": "RepDannyDavis",
    "votesmart_id": 233,
    "website": "https://davis.house.gov",
    "youtube_id": "dannykdavis07"
  },
  {
    "bioguide_id": "D000563",
    "birthday": "1944-11-21",
    "chamber": "senate",
    "contact_form": "https://www.durbin.senate.gov/contact/",
    "crp_id": "N00004981",
    "district": null,
    "facebook_id": "180436795325335",
    "fax": "202-228-0400",
    "fec_ids": [
      "S6IL00151",
      "H2IL20026"
    ],
    "first_name": "Richard",
    "gender": "M",
    "govtrack_id": "300038",
    "icpsr_id": 15021,
    "in_office": true,
    "last_name": "Durbin",
    "leadership_role": "Minority Whip",
    "lis_id": "S253",
    "middle_name": "J.",
    "name_suffix": null,
    "nickname": null,
    "oc_email": "Sen.Durbin@opencongress.org",
    "ocd_id": "ocd-division/country:us/state:il",
    "office": "711 Hart Senate Office Building",
    "party": "D",
    "phone": "202-224-2152",
    "senate_class": 2,
    "state": "IL",
    "state_name": "Illinois",
    "state_rank": "senior",
    "term_end": "2021-01-03",
    "term_start": "2015-01-06",
    "thomas_id": "00326",
    "title": "Sen",
    "twitter_id": "SenatorDurbin",
    "votesmart_id": 26847,
    "website": "http://www.durbin.senate.gov",
    "youtube_id": "SenatorDurbin"
  }
]`;

const sampleResponse = [
  {
    "bioguide_id": "D000622",
    "birthday": "1968-03-12",
    "chamber": "senate",
    "contact_form": "https://www.duckworth.senate.gov/content/contact-senator",
    "crp_id": "N00027860",
    "district": null,
    "facebook_id": "112300955610529",
    "fax": null,
    "fec_ids": [
      "H6IL06141",
      "S6IL00292"
    ],
    "first_name": "Tammy",
    "gender": "F",
    "govtrack_id": "412533",
    "icpsr_id": 21325,
    "in_office": true,
    "last_name": "Duckworth",
    "leadership_role": null,
    "lis_id": "S386",
    "middle_name": null,
    "name_suffix": null,
    "nickname": null,
    "oc_email": "Sen.Duckworth@opencongress.org",
    "ocd_id": "ocd-division/country:us/state:il",
    "office": "G12 Dirksen Senate Office Building",
    "party": "D",
    "phone": "202-224-2854",
    "senate_class": 3,
    "state": "IL",
    "state_name": "Illinois",
    "state_rank": "junior",
    "term_end": "2023-01-03",
    "term_start": "2017-01-03",
    "thomas_id": "02123",
    "title": "Sen",
    "twitter_id": "SenDuckworth",
    "votesmart_id": 57442,
    "website": "https://www.duckworth.senate.gov",
    "youtube_id": "repduckworth"
  },
  {
    "bioguide_id": "D000096",
    "birthday": "1941-09-06",
    "chamber": "house",
    "contact_form": null,
    "crp_id": "N00004884",
    "district": 7,
    "facebook_id": "280757931935749",
    "fax": "202-225-5641",
    "fec_ids": [
      "H4IL07037"
    ],
    "first_name": "Danny",
    "gender": "M",
    "govtrack_id": "400093",
    "icpsr_id": 29717,
    "in_office": true,
    "last_name": "Davis",
    "leadership_role": null,
    "middle_name": "K.",
    "name_suffix": null,
    "nickname": null,
    "oc_email": "Rep.Davis@opencongress.org",
    "ocd_id": "ocd-division/country:us/state:il/cd:7",
    "office": "2159 Rayburn House Office Building",
    "party": "D",
    "phone": "202-225-5006",
    "state": "IL",
    "state_name": "Illinois",
    "term_end": "2019-01-03",
    "term_start": "2017-01-03",
    "thomas_id": "01477",
    "title": "Rep",
    "twitter_id": "RepDannyDavis",
    "votesmart_id": 233,
    "website": "https://davis.house.gov",
    "youtube_id": "dannykdavis07"
  },
  {
    "bioguide_id": "D000563",
    "birthday": "1944-11-21",
    "chamber": "senate",
    "contact_form": "https://www.durbin.senate.gov/contact/",
    "crp_id": "N00004981",
    "district": null,
    "facebook_id": "180436795325335",
    "fax": "202-228-0400",
    "fec_ids": [
      "S6IL00151",
      "H2IL20026"
    ],
    "first_name": "Richard",
    "gender": "M",
    "govtrack_id": "300038",
    "icpsr_id": 15021,
    "in_office": true,
    "last_name": "Durbin",
    "leadership_role": "Minority Whip",
    "lis_id": "S253",
    "middle_name": "J.",
    "name_suffix": null,
    "nickname": null,
    "oc_email": "Sen.Durbin@opencongress.org",
    "ocd_id": "ocd-division/country:us/state:il",
    "office": "711 Hart Senate Office Building",
    "party": "D",
    "phone": "202-224-2152",
    "senate_class": 2,
    "state": "IL",
    "state_name": "Illinois",
    "state_rank": "senior",
    "term_end": "2021-01-03",
    "term_start": "2015-01-06",
    "thomas_id": "00326",
    "title": "Sen",
    "twitter_id": "SenatorDurbin",
    "votesmart_id": 26847,
    "website": "http://www.durbin.senate.gov",
    "youtube_id": "SenatorDurbin"
  }
]

export default states;

export { endpoints, sampleResponse, sampleResponseText }
